name: colab
workspace: /content
is_kaggle: true
use_apt: true
apt_packages:
  - libsparsehash-dev
kaggle:
  configure_api: false
  input_s3dis_dir: /content/s3dis_raw/Stanford3dDataset_v1.2
  input_s3dis_preprocessed_dir: /content/s3dis_preprocessed
torch:
  target_torch: ""
  target_torchvision: ""
  target_torchaudio: ""
  index_url: ""
spconv:
  cumm: ""
  spconv: ""
